import os
import json
import asyncio
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from rich.console import Console

# Import the core evolution engine from the root benchmark module
from benchmark import run_evolution

# Initialize FANG-grade terminal telemetry
console = Console()

app = FastAPI(
    title="SymboLR Local Compute Engine",
    description="High-performance FastAPI bridge connecting the React dashboard to the Rust/PyO3 Quality-Diversity Engine.",
    version="1.0.0"
)

# Allow React (Vite default port 5173) and any other origin to communicate without CORS blocks
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class EvolutionRequest(BaseModel):
    population_size: int
    generations: int
    target_epochs: int

@app.post("/api/evolve")
async def evolve_pipeline(req: EvolutionRequest):
    """
    Triggers the Quality-Diversity Genetic Programming engine.
    This executes synchronously on the local compute hardware but is offloaded to a thread pool 
    to prevent blocking the FastAPI event loop.
    """
    console.rule("[bold cyan]SymboLR: Incoming Web API Request[/bold cyan]")
    console.print(f"[bold green]Target Generations:[/bold green] {req.generations}")
    console.print(f"[bold green]Population Size:[/bold green] {req.population_size}")
    console.print(f"[bold green]Target Epochs:[/bold green] {req.target_epochs}")
    
    # We set a deterministic seed for reproducible artifact generation
    SEED = 42
    
    try:
        # Execute the heavy evolutionary run in a background thread to prevent blocking
        # This mirrors the execution flow of cli/main.py
        await asyncio.to_thread(
            run_evolution,
            generations=req.generations,
            pop_size=req.population_size,
            epochs=req.target_epochs,
            workers=4, # Use 4 workers by default for the local node
            seed=SEED,
            console=console,
            wandb_enabled=False
        )
        
        # Locate the artifact generated by diagnostics.py
        # Based on config.settings, the default export path is 'results/'
        artifact_path = os.path.join("results", f"run_seed{SEED}.json")
        
        if not os.path.exists(artifact_path):
            console.print("[bold red]ERROR: Evolution completed but artifact JSON was not found.[/bold red]")
            raise HTTPException(status_code=500, detail="Artifact generation failed.")
            
        with open(artifact_path, "r") as f:
            artifact_data = json.load(f)
            
        console.print("[bold green]SUCCESS: Transmitting artifact payload back to Web UI.[/bold green]")
        return artifact_data
        
    except Exception as e:
        console.print(f"[bold red]CRITICAL PIPELINE FAILURE:[/bold red] {str(e)}")
        raise HTTPException(status_code=500, detail=str(e))

if __name__ == "__main__":
    import uvicorn
    # Allow direct execution via `python api/main.py`
    console.print("[bold magenta]Booting SymboLR Local Compute Hub on port 8000...[/bold magenta]")
    uvicorn.run("api.main:app", host="0.0.0.0", port=8000, reload=True)
