import math
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import DataLoader

class FastConvNet(nn.Module):
    """
    A lightweight high performance Convolutional Neural Network optimized for RTX 4070 mixed precision through and rapid GP fitness evaluations.
    """
    def __init__(self, in_channels: int = 1, num_classes: int = 10):
        super().__init__()
        # Layer 1
        self.conv1 = nn.Conv2d(in_channels, 32, kernel_size=3, padding=1, bias=False)
        self.bn1 = nn.BatchNorm2d(32)
        # Layer 2
        self.conv2 = nn.Conv2d(32, 64, kernel_size=3, padding=1, bias=False)
        self.bn2 = nn.BatchNorm2d(64)
        
        self.pool = nn.MaxPool2d(kernel_size=2, stride=2)
        self.adaptive_pool = nn.AdaptiveAvgPool2d((4, 4))
        
        # Dense
        self.fc1 = nn.Linear(64 * 4 * 4, 128)
        self.fc2 = nn.Linear(128, num_classes)

    def forward(self, x:torch.Tensor) -> torch.Tensor:
        x = self.pool(F.relu(self.bn1(self.conv1(x))))
        x = self.pool(F.relu(self.bn2(self.conv2(x))))
        x = self.adaptive_pool(x)
        x = torch.flatten(x, 1)
        x = F.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
class ProbeTrainer:
    """
    Handles fast fitness evaluation of a learning rate schedule using AMP, stochastic data processing, and strict early-exit criteria
    """
    def __init__(
        self,
        device: torch.device,
        patience: int = 3,
        min_delta: float = 1e-3,
        explode_threshold: float = 10.0,
        amp_enabled: bool = True
    ):
        """
        Args:
            device: PyTorch device (cuda or cpu).
            patience: Number of validation checks with no improvement before exiting.
            min_delta: Minimum validation loss change to qualify as an improvement.
            explode_threshold: Loss threshold above which training is immediately aborted.
            amp_enabled: Whether to use Automatic Mixed Precision.
        """
        self.device = device
        self.patience = patience
        self.min_delta = min_delta
        self.explode_threshold = explode_threshold
        # Restrict AMP to CUDA to prevent CPU warning spam in fallback contexts
        self.amp_enabled = amp_enabled and device.type == 'cuda'

    def evaluate_schedule(
        self,
        model: nn.Module,
        train_loader: DataLoader,
        val_loader: DataLoader,
        lr_schedule: np.ndarray,
        epochs: int
    ) -> float:
        """
        Executes a training run using the provided learning rate schedule.
        
        Args:
            model: The neural network to train.
            train_loader: DataLoader for the training set.
            val_loader: DataLoader for the validation set.
            lr_schedule: A 1D numpy array of learning rates per global step.
            epochs: Total number of epochs to train.
            
        Returns:
            float: The best validation loss achieved (fitness metric).
                   Returns float('inf') if the model diverges early.
        """
        model = model.to(self.device)
        optimizer = torch.optim.SGD(model.parameters(), lr=1e-3, momentum=0.9, weight_decay=1e-4)
        criterion = nn.CrossEntropyLoss()
        
        scaler = torch.amp.GradScaler(enabled=self.amp_enabled)
        
        best_val_loss = float('inf')
        stagnant_epochs = 0
        global_step = 0
        schedule_length = len(lr_schedule)

        for epoch in range(epochs):
            model.train()
            
            for inputs, targets in train_loader:
                # 1. Fetch LR for the current global step
                if global_step < schedule_length:
                    current_lr = lr_schedule[global_step]
                else:
                    current_lr = lr_schedule[-1]  # Fallback to final schedule value
                    
                # 2. Defend against mathematically absurd LR schedules generated by GP
                if not math.isfinite(current_lr) or current_lr <= 0.0 or current_lr > 10.0:
                    return float('inf')
                    
                for param_group in optimizer.param_groups:
                    param_group['lr'] = float(current_lr)
                    
                inputs, targets = inputs.to(self.device), targets.to(self.device)
                optimizer.zero_grad(set_to_none=True)
                
                # 3. Mixed Precision Forward Pass
                with torch.autocast(device_type=self.device.type, enabled=self.amp_enabled):
                    outputs = model(inputs)
                    loss = criterion(outputs, targets)
                
                # 4. Immediate Divergence Check (Exploding Gradients)
                if not math.isfinite(loss.item()) or loss.item() > self.explode_threshold:
                    return float('inf')  # Penalize fitness completely
                
                # 5. Mixed Precision Backward Pass
                scaler.scale(loss).backward()
                scaler.step(optimizer)
                scaler.update()
                
                global_step += 1
                
            # End of Epoch Validation Sweep
            val_loss = self._validate(model, val_loader, criterion)
            
            if not math.isfinite(val_loss):
                return float('inf')
            
            # 6. Early Exit: Stagnation Check
            if val_loss < best_val_loss - self.min_delta:
                best_val_loss = val_loss
                stagnant_epochs = 0
            else:
                stagnant_epochs += 1
                
            if stagnant_epochs >= self.patience:
                break  # Short-circuit to hand CPU back to GP evolution

        return float(best_val_loss)

    @torch.no_grad()
    def _validate(self, model: nn.Module, val_loader: DataLoader, criterion: nn.Module) -> float:
        model.eval()
        total_loss = 0.0
        batches = 0
        
        for inputs, targets in val_loader:
            inputs, targets = inputs.to(self.device), targets.to(self.device)
            with torch.autocast(device_type=self.device.type, enabled=self.amp_enabled):
                outputs = model(inputs)
                loss = criterion(outputs, targets)
            total_loss += loss.item()
            batches += 1
            
        return total_loss / max(1, batches)
